# Plotting a 2 by 2 array of graphs
png(filename="plot4.png")
par(mfrow=c(2,2))
plot(plotdata[,3],type="l",ylab="Global Active Power (kilowatts)",xaxt='n',xlab='')
axis(1, at=c(20,1450,2900), labels=c("Thu","Fri","Sat"))
plot(plotdata[,5],type="l",ylab="Voltage",xaxt='n',xlab="datetime")
axis(1, at=c(20,1450,2900), labels=c("Thu","Fri","Sat"))
plot(plotdata[,7],type="l",ylab="Energy sub metering",xaxt='n', col="black",xlab='')
lines(plotdata[,8], type="l", col="red")
lines(plotdata[,9], type="l", col="blue")
axis(1, at=c(20,1450,2900), labels=c("Thu","Fri","Sat"))
legend(750,39.25,col=c("black", "red", "blue"),lty=c(1,1,1), c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),box.col=0)
plot(plotdata[,4],type="l",ylab="Global_reactive_power",xaxt='n',xlab="datetime")
axis(1, at=c(20,1450,2900), labels=c("Thu","Fri","Sat"))
dev.off()